version: "3.7"
services:
    app:
        build:
            args:
                user: sammy
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: fileupload
        container_name: file_upload-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - file_upload
    db:
        image: mysql:8.0
        container_name: db-app
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 3311:3306
        volumes:
            - ./docker-compose/mysql/mysql:/var/lib/mysql/:rw
            - ./docker-compose/mysql/init:/docker-entrypoint-initdb.d/:ro
        networks:
            - file_upload
    nginx:
        image: nginx:alpine
        container_name: nginx-app
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - file_upload
networks:
  file_upload:
      driver: bridge
